name: Scheduled Branch Name First one

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  schedule:
    name: ðŸ“… Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.TOKEN }}
          date: ${{ github.event.inputs.date }}
          workflow: 'basic.yml'
          ref: main
          wait-ms: 45000
